spring.application.name=ProNightPassesManagementSystem

#database configuration for mysql

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/Passes}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hiernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#LINK to generate passkey : http://myaccount.google.com/appasswords
#uhwt bzwt qdiw scys

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.requried=true

## Razor Pay Key 
razorpay.key_id=${RAZORPAY_KEY_ID:}
razorpay.key_secret=${RAZORPAY_KEY_SECRET:}

# AI
gemini.api.key=${GEMINI_API_KEY:}
